id: I7C2FD4E5
legacy_id: P009373
ocr_import_info:
  bdrc_scan_id: W2PD19981
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T05:12:20'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T11:04:04.116178+00:00'
last_modified: 2022-09-03 19:04:17.283128
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2PD19981
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2PD19981
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཀརྨ་ཀཾ་ཚང་གི་རང་ལུགས་ཕག་མོ་བདེ་མཆོག་རྒྱལ་བ་རྒྱ་མཚོའི་ཆོ་ག་རྣམ་གསུམ།
statistics:
  ocr_word_mean_confidence_index: 0.916429777174609
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I2PD19991:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19991
      total_pages: 450
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD19991.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.916429777174609
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
