id: I7C2FD4E5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T05:15:16+00:00'
last_modified: '2022-06-08T10:33:09.662049+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD19981
  title: 'ཀརྨ་ཀཾ་ཚང་གི་རང་ལུགས་ཕག་མོ་བདེ་མཆོག་རྒྱལ་བ་རྒྱ་མཚོའི་ཆོ་ག་རྣམ་གསུམ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1D33:
      image_group_id: I2PD19991
      title: ''
      total_pages: 450
      order: 1
      base_file: 1D33.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
