id: P009373
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2PD19981
  title: 'ཀརྨ་ཀཾ་ཚང་གི་རང་ལུགས་ཕག་མོ་བདེ་མཆོག་རྒྱལ་བ་རྒྱ་མཚོའི་ཆོ་ག་རྣམ་གསུམ། '
  author: ''
  volumes:
    a0a45d7b116e4643a1603a83fafb1de4:
      image_group_id: I2PD19991
      title: ''
      volume_number: 1
      total_pages: 450
      base_file: v001.txt
